version: '3.8'

services:
  source:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: "line-bot-monthly-seminar"
    restart: always
    ports:
      - 8080:8080
    command: "python ./main.py"
