version: '3.8'

services:
  source:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: "line-bot-monthly-seminar"
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 80:80
    command: "python -u ./main.py"
