name: Github Actions

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Dockerhub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_REPO }}:latest

  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    environment: 'prod'
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Deploy Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.USERNAME }}
          script: |
            docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password=${{ secrets.DOCKERHUB_TOKEN }}
            docker pull ${{ secrets.DOCKERHUB_REPO }}:latest
            docker rm -f -v faang-ez-line-bot || true
            docker run --detach --name faang-ez-line-bot --env "VIRTUAL_HOST=${{ secrets.VIRTUAL_HOST }}" --env "LETSENCRYPT_HOST=${{ secrets.VIRTUAL_HOST }}" --env "LINE_CHANNEL_ACCESS_TOKEN=${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}" --env="LINE_CHANNEL_SECRET=${{ secrets.LINE_CHANNEL_SECRET }}" --env "GROUP_ID=${{ secrets.GROUP_ID }}" --env="WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }}" --expose 80 ${{ secrets.DOCKERHUB_REPO }} python ./main.py